import type { ResolvedLocation, Weather } from '@/lib/context';

export type User={id:string;display_name:string;email:string;country?:string;city?:string;state_or_region?:string};
export type Cuisine={id:string;name:string};
export type Profile={diet_type:string;spice_tolerance:number;adventurousness:number;usual_budget_min:string;usual_budget_max:string;usual_travel_radius_miles:string;dining_preferences:string[];cuisine_preferences:{name:string;preference_level:number}[];comfort_foods:string[];allergies:{name:string;notes?:string}[]};
export type Restaurant={id:string;provider:string;name:string;categories:string[];latitude:number;longitude:number;address:string|null;city:string|null;distance_miles:number;rating:number|null;review_count:number|null;price_level:number|null;open_now:boolean|null;website:string|null};
export type RestaurantSearchRequest={latitude:number;longitude:number;radius_miles:number;query?:string;cuisine?:string;limit?:number};
export class ApiError extends Error{constructor(message:string,readonly status:number){super(message)}}
const base=process.env.NEXT_PUBLIC_API_URL??'http://localhost:8000';
async function req<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(base+path,init);if(!r.ok){throw new ApiError(r.status===503?'Live restaurant discovery is not configured right now.':'Ahara cannot reach its local service right now.',r.status)}return r.json() as Promise<T>}
function restaurantQuery(input:RestaurantSearchRequest):string{const params=new URLSearchParams({latitude:String(input.latitude),longitude:String(input.longitude),radius_miles:String(input.radius_miles),limit:String(input.limit??6)});if(input.query)params.set('query',input.query);if(input.cuisine)params.set('cuisine',input.cuisine);return '/api/v1/restaurants/search?'+params.toString()}
export const api={cuisines:()=>req<Cuisine[]>('/api/v1/cuisines'),user:(id:string)=>req<User>('/api/v1/users/'+id),profile:(id:string)=>req<Profile>('/api/v1/users/'+id+'/food-profile'),onboard:(body:unknown)=>req<{user:User;food_profile:Profile}>('/api/v1/onboarding',{method:'POST',body:JSON.stringify(body)}),update:(id:string,body:unknown)=>req<Profile>('/api/v1/users/'+id+'/food-profile',{method:'PUT',body:JSON.stringify(body)}),resolveLocation:(query:string)=>req<ResolvedLocation>('/api/v1/location/resolve?query='+encodeURIComponent(query)),weather:(lat:number,lon:number)=>req<Weather>('/api/v1/context/weather?latitude='+lat+'&longitude='+lon),searchRestaurants:(input:RestaurantSearchRequest)=>req<Restaurant[]>(restaurantQuery(input))};
export type ApiHealth={status:'healthy'|'degraded'|'unhealthy';service:string;version:string;database:'healthy'|'unhealthy';redis:'healthy'|'unhealthy'};
export function getApiHealth():Promise<ApiHealth>{return req<ApiHealth>('/api/v1/health')}