'use client';

import {useCallback, useEffect, useRef, useState} from 'react';
import {api} from '@/lib/api';
import {Weather, ResolvedLocation, contextCopy, mealAt, saved} from '@/lib/context';

type ContextBarProps = {profileCity?: string; onLocationChange?: (location: ResolvedLocation) => void};

export function ContextBar({profileCity, onLocationChange}: ContextBarProps) {
  const [loc, setLoc] = useState<ResolvedLocation>(); const [weather, setWeather] = useState<Weather>(); const [query, setQuery] = useState(''); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const containerRef = useRef<HTMLElement>(null);
  const load = useCallback(async (location: ResolvedLocation) => { setLoading(true); setError(''); try { const nextWeather = await api.weather(location.latitude, location.longitude); setLoc(location); setWeather(nextWeather); onLocationChange?.(location); localStorage.setItem('ahara_context_location', JSON.stringify({city: location.city, state_or_region: location.state_or_region, country: location.country, display_name: location.display_name})); setOpen(false); } catch { setError('Weather is not available right now.'); } finally { setLoading(false); } }, [onLocationChange]);
  useEffect(() => { const stored = saved(localStorage.getItem('ahara_context_location')); if (stored) api.resolveLocation(`${stored.city}, ${stored.state_or_region}`).then(load).catch(() => localStorage.removeItem('ahara_context_location')); }, [load]);
  useEffect(() => { const outside = (event: MouseEvent) => { if (!loading && containerRef.current && !containerRef.current.contains(event.target as Node)) setOpen(false); }; const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false); }; document.addEventListener('mousedown', outside); document.addEventListener('keydown', escape); return () => { document.removeEventListener('mousedown', outside); document.removeEventListener('keydown', escape); }; }, [loading]);
  const manual = async () => { try { await load(await api.resolveLocation(query)); } catch { setError("I couldn't find that location. Try a city and state."); } };
  const device = () => { if (!navigator.geolocation) { setError('Location is not supported. Use a city instead.'); return; } setLoading(true); setError(''); navigator.geolocation.getCurrentPosition(position => { void load({latitude: position.coords.latitude, longitude: position.coords.longitude, city: 'Current location', state_or_region: '', country: '', display_name: 'Current location'}); }, geolocationError => { setLoading(false); setError(geolocationError.code === 1 ? 'Location access is off. Use your profile city or enter another city.' : geolocationError.code === 3 ? "We couldn't get your location in time." : 'Location is unavailable.'); }, {timeout: 8000, maximumAge: 300000}); };
  return <section className="context" ref={containerRef}><button aria-label="Change location" onClick={() => setOpen(value => !value)}>{loc?.display_name || profileCity || 'Set your location'}</button>{weather && <><span>{Math.round(weather.temperature)}°F · {weather.condition} · {mealAt(weather.timezone)}</span><p>{contextCopy(weather)}</p></>}{open && <div className="picker"><p>Ahara uses your location to understand the weather and nearby food.</p><button disabled={loading} onClick={device}>Use my location</button>{profileCity && <button disabled={loading} onClick={() => void api.resolveLocation(profileCity).then(load).catch(() => setError("I couldn't find that location. Try a city and state."))}>Use {profileCity}</button>}<label>Enter another city<input value={query} disabled={loading} onChange={event => setQuery(event.target.value)} placeholder="Dallas, TX"/></label><button disabled={loading || !query.trim()} onClick={() => void manual()}>Find location</button>{loading && <p role="status">Getting the weather...</p>}{error && <p role="alert">{error}</p>}</div>}</section>;
}